"""Configuration file for campstatus

"""

# Defines which forest's campgrounds to scrape
# key can be any text string
# value must be a valid URL
forest_urls = {
     'Stanislaus': 'https://www.fs.usda.gov/activity/stanislaus/recreation/camping-cabins/?recid=14833&actid=29',
     'Tahoe': 'https://www.fs.usda.gov/activity/tahoe/recreation/camping-cabins/?recid=55444&actid=29',
    'El Dorado': 'https://www.fs.usda.gov/activity/eldorado/recreation/camping-cabins/?recid=71008&actid=29'
}

# desired final columns in the final table
campgrounds_final_table_columns = [
    'Campground',
    'Status',
    'Fees',
    'Open Season',
    'Reservations',
    'Restroom',
    'Potable Water',
    'Elevation',
    'Latitude',
    'Longitude',
    'Usage',
    'Water',
    'URL',
    ]

# list of forests to scrape
forests_to_scrape = [
	'stanislaus',
	'eldorado',
	'tahoe',
	'mendocino',
	'plumas',
	'lassen',
	'stnf',
	'sierra',
]

# full list of national forest URL descriptors as keys, and full names
# as the values. Use the keys in this list to fill out "forests_to_scrape"
# config variable

AllNationalForests = {
'allegheny':         'Allegheny National Forest',
'angeles':           'Angeles National Forest',
'asnf':              'Apache-Sitgreaves National Forest',
'apalachicola':      'Apalachicola National Forest',
'arp':               'Arapaho and Roosevelt National Forests and Pawnee National Grassland',
'ashley':            'Ashley National Forest',
'bdnf':              'Beaverhead-Deerlodge National Forest',
'bighorn':           'Bighorn National Forest',
'bitterroot':        'Bitterroot National Forest',
'blackhills':        'Black Hills National Forest',
'boise':             'Boise National Forest',
'btnf':              'Bridger-Teton National Forest',
'ctnf':              'Caribou-Targee National Forest',
'carson':            'Carson National Forest',
'conf':              'Chattahoochee-Oconee National Forest',
'cnnf':              'Chequamegon-Nicolet National Forest',
'cherokee':          'Cherokee National Forest',
'chippewa':          'Chippewa National Forest',
'chugach':           'Chugach National Forest',
'cibola':            'Cibola National Forest',
'cleveland':         'Cleveland National Forest',
'coconino':          'Coconino National Forest',
'colville':          'Colville National Forest',
'coronado':          'Coronado National Forest',
'custergallatin':    'Custer National Forest',
'dpg':               'Dakota Prairie National Forest',
'dbnf':              'Daniel Boone National Forest',
'deschutes':         'Deschutes National Forest',
'dixie':             'Dixie National Forest',
'elyunque':          'El Yunque National Forest',
'eldorado':          'Eldorado National Forest ',
'fishlake':          'Fishlake National Forest',
'flathead':          'Flathead National Forest',
'fnst':              'Florida National Scenic Trail',
'scnfs':             'Francis Marion & Sumter National Forests ',
'fremont-winema':    'Fremont-Winema National Forests',
'gwj':               'George Washington & Jefferson National Forest ',
'giffordpinchot':    'Gifford Pinchot National Forest',
'gila':              'Gila National Forest',
'gmug':              'Grand Mesa, Uncompahgre and Gunnison National Forests',
'gmfl':              'Green Mountain and Finger Lakes National Forest',
'hlcnf':             'Helena-Lewis and Clark National Forest',
'hiawatha':          'Hiawatha National Forest',
'hoosier':           'Hoosier National Forest',
'htnf':              'Humboldt-Toiyabe National Forest',
'hmnf':              'Huron-Manistee National Forest',
'ipnf':              'Idaho Panhandle National Forest',
'inyo':              'Inyo National Forest',
'kaibab':            'Kaibab National Forest',
'kisatchie':         'Kisatchie National Forest',
'klamath':           'Klamath National Forest',
'kootenai':          'Kootenai National Forest',
'ltbmu':             'Lake Tahoe Basin Management Unit',
'lassen':            'Lassen National Forest',
'lincoln':           'Lincoln National Forest',
'lolo':              'Lolo National Forest',
'lpnf':              'Los Padres National Forest',
'malheur':           'Malheur National Forest',
'mantilasal':        'Manti-LaSal National Forest',
'mtnf':              'Mark Twain National Forest',
'mbr':               'Medicine Bow and Routt National Forests and Thunder Basin National Grassland',
'mendocino':         'Mendocino National Forest',
'midewin':           'Midewin National Forest',
'modoc':             'Modoc National Forest',
'mnf':               'Monongahela National Forest',
'mbs':               'Mt. Baker-Snoqualmie National Forest',
'mthood':            'Mt. Hood National Forest',
'alabama':           'National Forests in Alabama',
'nfsnc':             'National Forests in North Carolina',
'texas':             'National Forests in Texas',
'mississippi':       'National Forests of Mississippi',
'nebraska':          'Nebraska National Forests and Grasslands',
'ocala':             'Ocala National Forest',
'ochoco':            'Ochoco National Forests, Crooked River National Grassland',
'okawen':            'Okanagon-Wenatchee National Forest',
'olympic':           'Olympic National Forest',
'osceola':           'Osceola National Forest',
'ottawa':            'Ottawa National Forest',
'ouachita':          'Ouachita National Forest',
'osfnf':             'Ozark-St Francis National Forests',
'payette':           'Payette National Forest',
'psicc':             'Pike and San Isabel National Forests and Cimarron-Comanche National Grasslands',
'plumas':            'Plumas National Forest',
'prescott':          'Prescott National Forest',
'riogrande':         'Rio Grande National Forest',
'rogue-siskiyou':    'Rogue River-Siskyou National Forest',
'scnf':              'Salmon Challis National Forest',
'sbnf':              'San Bernardino National Forest',
'sanjuan':           'San Juan National Forest',
'santafe':           'Santa Fe National Forest',
'savannahriver':     'Savannah River Natural Resource Management & Research Institute',
'sawtooth':          'Sawtooth National Forest',
'sequoia':           'Sequoia National Forest',
'stnf':              'Shasta-Trinity National Forest',
'shawnee':           'Shawnee National Forest',
'shoshone':          'Shoshone National Forest',
'crgnsa':            'Shoshone National Forest',
'sierra':            'Sierra National Forest ',
'siuslaw':           'Siuslaw National Forest',
'srnf':              'Six Rivers National Forest',
'stanislaus':        'Stanislaus National Forest',
'superior':          'Superior National Forest',
'tahoe':             'Tahoe National Forest',
'tongass':           'Tongass National Forest',
'tonto':             'Tonto National Forest',
'uwcnf':             'Uinta-Wasatch-Cache National Forest',
'umatilla':          'Umatilla National Forest',
'umpqua':            'Umpqua National Forest',
'wallowa-whitman':   'Wallowa-Whitman National Forest',
'wayne':             'Wayne National Forest',
'whitemountain':     'White Mountain National Forest',
'whiteriver':        'White River National Forest',
'willamette':        'Willamette National Forest',
}